# Generated by Django 4.2.7 on 2023-11-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('registry_date', models.DateTimeField()),
            ],
        ),
    ]
